name: "longbui-blog"
services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-13}
    ports:
      - "5444:5432"
    volumes:
      - ./:/opt
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: longbui
      POSTGRES_PASSWORD: longbui
    tty: true
  
  elasticsearch:
    image: elasticsearch:8.15.5
    volumes:
      - elasticsearch_data:/var/lib/elasticsearch/data
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - 9200:9200
      - 9300:9300
  
  kibana:
    image: kibana:7.17.26
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

volumes:
  postgres_data:
  elasticsearch_data:
