---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: blog
type: Opaque
stringData:
  # These are the initial superuser credentials
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres123     # Set a secure password
  POSTGRES_DB: blogdb

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-config
  labels:
    app: blog
data:
  PROJECT_NAME: BlogAPI
  DATABASE_URL: postgres://postgres:postgres123@postgres-service.blog:5432/blogdb
  SECRET_KEY: your-secret-key
  ALGORITHM: HS256
  ACCESS_TOKEN_EXPIRE_MINUTES: '30'
  ALLOWED_ORIGINS: http://localhost:3000
  LOG_FILE: /opt/logs/app.log
  ELASTICSEARCH_HOST: http://elasticsearch:9200
  ATTACHMENT_PATH: /opt/storage
