pipeline {
    agent any
    environment {
        HOST_BUILD_WORKSPACE = "/opt/source/porfolio/blogs"
        HOST_SERVICE_NAME = "blogserver"
        // --
        HOST_SSH_CREDENTIAL = "longbui_ssh_userpasswd"
        HOST_SSH_IP_NAME = "longbui-vm-ip"
        HOST_SSH_CREDS = credentials("${env.HOST_SSH_CREDENTIAL}")
        HOST_SSH_IP = credentials("${env.HOST_SSH_IP_NAME}")
        HOST_SSH_TIMEOUT = 10

    }

    stages {
        stage('1.SYNC') {
            steps {
                echo "============================ 1. SYNC ====================================================="
                    sh """sudo rsync "$env.WORKSPACE/" "$HOST_BUILD_WORKSPACE/" """
            }
        }
        stage("2. Build React App"){
            steps {
                echo "============================ 2. BUILD ====================================================="
                sh """sudo cd $HOST_BUILD_WORKSPACE/ui && sudo npm install && sudo npm run build """
            }
        }
        stage("3. Reload Service"){
            steps {
                echo "============================ 6. DEPLOY ====================================================="
                sh """ sudo systemctl restart $HOST_SERVICE_NAME """
            }
        }
    }
}